[package]
name = "labyrinth"
version = "0.0.4"
edition = "2024"
license = "MIT"
description = "Library for managing soaricarus storage"

[dependencies]
aws-config = { version = "1.10.1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.138.1" }
time = "0.3.53"
tokio = { version = "1.53.0", features = ["full"] }
uuid = "1.24.0"
